### ISSUE TITLE
I love this project... is it considered ready for primetime?

### ISSUE THREAD

**Issue by dfuentes77** [rubys/dockerfile-rails#20]
If so, are you able to add a a Changelog file or Release Notes for the tags, in order to show the purpose behind the updates.  I've tried to follow the commits but it's hard to get a high level view of the purpose for the updates.   

Much appreciated for the time spent on this.  Impressive project.  Thanks!

**Comment by rubys** [comment]
Thanks!

It is being used in production at fly.io since 29 January 2023: https://community.fly.io/t/cut-over-to-rails-dockerfile-generator-on-sunday-29-jan-2023/10350

I've created a Github release for 1.2.0.  One nice side effect of capturing test results is that the diff included with the release will show examples of what changed.  I plan to do this going forward.

Feel free to reopen this issue if this doesn't meet your needs.
